// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("planetscale");

/**
 * Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_NAME`. Mutually exclusive with
 * `serviceTokenName` and `serviceToken`.
 */
export declare const accessToken: string | undefined;
Object.defineProperty(exports, "accessToken", {
    get() {
        return __config.get("accessToken");
    },
    enumerable: true,
});

/**
 * If set, points the API client to a different endpoint than `https:://api.planetscale.com/v1`.
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint");
    },
    enumerable: true,
});

/**
 * Value of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN`. Mutually exclusive with
 * `accessToken`.
 */
export declare const serviceToken: string | undefined;
Object.defineProperty(exports, "serviceToken", {
    get() {
        return __config.get("serviceToken");
    },
    enumerable: true,
});

/**
 * Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_NAME`. Mutually exclusive with
 * `accessToken`.
 */
export declare const serviceTokenName: string | undefined;
Object.defineProperty(exports, "serviceTokenName", {
    get() {
        return __config.get("serviceTokenName");
    },
    enumerable: true,
});

