// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/sst/pulumi-planetscale/sdk/go/planetscale/internal"
)

var _ = internal.GetEnvOrDefault

// Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_NAME`. Mutually exclusive with
// `serviceTokenName` and `serviceToken`.
func GetAccessToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "planetscale:accessToken")
}

// If set, points the API client to a different endpoint than `https:://api.planetscale.com/v1`.
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "planetscale:endpoint")
}

// Value of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN`. Mutually exclusive with
// `accessToken`.
func GetServiceToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "planetscale:serviceToken")
}

// Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_NAME`. Mutually exclusive with
// `accessToken`.
func GetServiceTokenName(ctx *pulumi.Context) string {
	return config.Get(ctx, "planetscale:serviceTokenName")
}
