// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package planetscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sst/pulumi-planetscale/sdk/go/planetscale/internal"
)

// Linting errors for the schema of a PlanetScale branch.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/sst/pulumi-planetscale/sdk/go/planetscale"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example, err := planetscale.GetBranchSchemaLint(ctx, &planetscale.GetBranchSchemaLintArgs{
//				Organization: "example.com",
//				Database:     "example_db",
//				Branch:       "main",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("schemaLint", example)
//			return nil
//		})
//	}
//
// ```
func GetBranchSchemaLint(ctx *pulumi.Context, args *GetBranchSchemaLintArgs, opts ...pulumi.InvokeOption) (*GetBranchSchemaLintResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetBranchSchemaLintResult
	err := ctx.Invoke("planetscale:index/getBranchSchemaLint:getBranchSchemaLint", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBranchSchemaLint.
type GetBranchSchemaLintArgs struct {
	Branch       string `pulumi:"branch"`
	Database     string `pulumi:"database"`
	Organization string `pulumi:"organization"`
}

// A collection of values returned by getBranchSchemaLint.
type GetBranchSchemaLintResult struct {
	Branch   string                     `pulumi:"branch"`
	Database string                     `pulumi:"database"`
	Errors   []GetBranchSchemaLintError `pulumi:"errors"`
	// The provider-assigned unique ID for this managed resource.
	Id           string `pulumi:"id"`
	Organization string `pulumi:"organization"`
}

func GetBranchSchemaLintOutput(ctx *pulumi.Context, args GetBranchSchemaLintOutputArgs, opts ...pulumi.InvokeOption) GetBranchSchemaLintResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetBranchSchemaLintResult, error) {
			args := v.(GetBranchSchemaLintArgs)
			r, err := GetBranchSchemaLint(ctx, &args, opts...)
			var s GetBranchSchemaLintResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetBranchSchemaLintResultOutput)
}

// A collection of arguments for invoking getBranchSchemaLint.
type GetBranchSchemaLintOutputArgs struct {
	Branch       pulumi.StringInput `pulumi:"branch"`
	Database     pulumi.StringInput `pulumi:"database"`
	Organization pulumi.StringInput `pulumi:"organization"`
}

func (GetBranchSchemaLintOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBranchSchemaLintArgs)(nil)).Elem()
}

// A collection of values returned by getBranchSchemaLint.
type GetBranchSchemaLintResultOutput struct{ *pulumi.OutputState }

func (GetBranchSchemaLintResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBranchSchemaLintResult)(nil)).Elem()
}

func (o GetBranchSchemaLintResultOutput) ToGetBranchSchemaLintResultOutput() GetBranchSchemaLintResultOutput {
	return o
}

func (o GetBranchSchemaLintResultOutput) ToGetBranchSchemaLintResultOutputWithContext(ctx context.Context) GetBranchSchemaLintResultOutput {
	return o
}

func (o GetBranchSchemaLintResultOutput) Branch() pulumi.StringOutput {
	return o.ApplyT(func(v GetBranchSchemaLintResult) string { return v.Branch }).(pulumi.StringOutput)
}

func (o GetBranchSchemaLintResultOutput) Database() pulumi.StringOutput {
	return o.ApplyT(func(v GetBranchSchemaLintResult) string { return v.Database }).(pulumi.StringOutput)
}

func (o GetBranchSchemaLintResultOutput) Errors() GetBranchSchemaLintErrorArrayOutput {
	return o.ApplyT(func(v GetBranchSchemaLintResult) []GetBranchSchemaLintError { return v.Errors }).(GetBranchSchemaLintErrorArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetBranchSchemaLintResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetBranchSchemaLintResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetBranchSchemaLintResultOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v GetBranchSchemaLintResult) string { return v.Organization }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetBranchSchemaLintResultOutput{})
}
