// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A list of PlanetScale backups.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as planetscale from "@pulumi/planetscale";
 *
 * const example = planetscale.getBackups({
 *     organization: "example.com",
 *     database: "example_db",
 *     branch: "main",
 * });
 * export const backups = example;
 * ```
 */
export function getBackups(args: GetBackupsArgs, opts?: pulumi.InvokeOptions): Promise<GetBackupsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("planetscale:index/getBackups:getBackups", {
        "branch": args.branch,
        "database": args.database,
        "organization": args.organization,
    }, opts);
}

/**
 * A collection of arguments for invoking getBackups.
 */
export interface GetBackupsArgs {
    branch: string;
    database: string;
    organization: string;
}

/**
 * A collection of values returned by getBackups.
 */
export interface GetBackupsResult {
    readonly backups: outputs.GetBackupsBackup[];
    readonly branch: string;
    readonly database: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly organization: string;
}
/**
 * A list of PlanetScale backups.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as planetscale from "@pulumi/planetscale";
 *
 * const example = planetscale.getBackups({
 *     organization: "example.com",
 *     database: "example_db",
 *     branch: "main",
 * });
 * export const backups = example;
 * ```
 */
export function getBackupsOutput(args: GetBackupsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetBackupsResult> {
    return pulumi.output(args).apply((a: any) => getBackups(a, opts))
}

/**
 * A collection of arguments for invoking getBackups.
 */
export interface GetBackupsOutputArgs {
    branch: pulumi.Input<string>;
    database: pulumi.Input<string>;
    organization: pulumi.Input<string>;
}
