// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The schema of a PlanetScale branch.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as planetscale from "@pulumi/planetscale";
 *
 * const example = planetscale.getBranchSchema({
 *     organization: "example.com",
 *     database: "example_db",
 *     branch: "main",
 * });
 * export const branchSchema = example;
 * ```
 */
export function getBranchSchema(args: GetBranchSchemaArgs, opts?: pulumi.InvokeOptions): Promise<GetBranchSchemaResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("planetscale:index/getBranchSchema:getBranchSchema", {
        "branch": args.branch,
        "database": args.database,
        "keyspace": args.keyspace,
        "organization": args.organization,
    }, opts);
}

/**
 * A collection of arguments for invoking getBranchSchema.
 */
export interface GetBranchSchemaArgs {
    branch: string;
    database: string;
    keyspace?: string;
    organization: string;
}

/**
 * A collection of values returned by getBranchSchema.
 */
export interface GetBranchSchemaResult {
    readonly branch: string;
    readonly database: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly keyspace?: string;
    readonly organization: string;
    readonly tables: outputs.GetBranchSchemaTable[];
}
/**
 * The schema of a PlanetScale branch.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as planetscale from "@pulumi/planetscale";
 *
 * const example = planetscale.getBranchSchema({
 *     organization: "example.com",
 *     database: "example_db",
 *     branch: "main",
 * });
 * export const branchSchema = example;
 * ```
 */
export function getBranchSchemaOutput(args: GetBranchSchemaOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetBranchSchemaResult> {
    return pulumi.output(args).apply((a: any) => getBranchSchema(a, opts))
}

/**
 * A collection of arguments for invoking getBranchSchema.
 */
export interface GetBranchSchemaOutputArgs {
    branch: pulumi.Input<string>;
    database: pulumi.Input<string>;
    keyspace?: pulumi.Input<string>;
    organization: pulumi.Input<string>;
}
