// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Linting errors for the schema of a PlanetScale branch.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as planetscale from "@pulumi/planetscale";
 *
 * const example = planetscale.getBranchSchemaLint({
 *     organization: "example.com",
 *     database: "example_db",
 *     branch: "main",
 * });
 * export const schemaLint = example;
 * ```
 */
export function getBranchSchemaLint(args: GetBranchSchemaLintArgs, opts?: pulumi.InvokeOptions): Promise<GetBranchSchemaLintResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("planetscale:index/getBranchSchemaLint:getBranchSchemaLint", {
        "branch": args.branch,
        "database": args.database,
        "organization": args.organization,
    }, opts);
}

/**
 * A collection of arguments for invoking getBranchSchemaLint.
 */
export interface GetBranchSchemaLintArgs {
    branch: string;
    database: string;
    organization: string;
}

/**
 * A collection of values returned by getBranchSchemaLint.
 */
export interface GetBranchSchemaLintResult {
    readonly branch: string;
    readonly database: string;
    readonly errors: outputs.GetBranchSchemaLintError[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly organization: string;
}
/**
 * Linting errors for the schema of a PlanetScale branch.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as planetscale from "@pulumi/planetscale";
 *
 * const example = planetscale.getBranchSchemaLint({
 *     organization: "example.com",
 *     database: "example_db",
 *     branch: "main",
 * });
 * export const schemaLint = example;
 * ```
 */
export function getBranchSchemaLintOutput(args: GetBranchSchemaLintOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetBranchSchemaLintResult> {
    return pulumi.output(args).apply((a: any) => getBranchSchemaLint(a, opts))
}

/**
 * A collection of arguments for invoking getBranchSchemaLint.
 */
export interface GetBranchSchemaLintOutputArgs {
    branch: pulumi.Input<string>;
    database: pulumi.Input<string>;
    organization: pulumi.Input<string>;
}
