// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A list of PlanetScale OAuth applications. (requires feature flag)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as planetscale from "@pulumi/planetscale";
 *
 * const example = planetscale.getOauthApplications({
 *     organization: data.planetscale_organization.example.name,
 * });
 * export const oauthApps = example;
 * ```
 */
export function getOauthApplications(args: GetOauthApplicationsArgs, opts?: pulumi.InvokeOptions): Promise<GetOauthApplicationsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("planetscale:index/getOauthApplications:getOauthApplications", {
        "organization": args.organization,
    }, opts);
}

/**
 * A collection of arguments for invoking getOauthApplications.
 */
export interface GetOauthApplicationsArgs {
    organization: string;
}

/**
 * A collection of values returned by getOauthApplications.
 */
export interface GetOauthApplicationsResult {
    readonly applications: outputs.GetOauthApplicationsApplication[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly organization: string;
}
/**
 * A list of PlanetScale OAuth applications. (requires feature flag)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as planetscale from "@pulumi/planetscale";
 *
 * const example = planetscale.getOauthApplications({
 *     organization: data.planetscale_organization.example.name,
 * });
 * export const oauthApps = example;
 * ```
 */
export function getOauthApplicationsOutput(args: GetOauthApplicationsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOauthApplicationsResult> {
    return pulumi.output(args).apply((a: any) => getOauthApplications(a, opts))
}

/**
 * A collection of arguments for invoking getOauthApplications.
 */
export interface GetOauthApplicationsOutputArgs {
    organization: pulumi.Input<string>;
}
